version: '2'
services:
    webscrap:
        network_mode: host
        container_name: webscrap
        build:
            context: webscrap
            dockerfile: Dockerfile
        image: webscrap:latest
        ports:
            - 8081:8081
        
    scrapstore:
        network_mode: host
        container_name: scrapstore
        build:
            context: scrapstore
            dockerfile: Dockerfile
        image: scrapstore:latest
        ports:
            - 8082:8082
        expose:
            - 8082
            
    elasticsearch:
        network_mode: host
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        container_name: elasticsearch
        environment:
            - node.name=elasticsearch
            - bootstrap.memory_lock=true
            - discovery.seed_hosts=localhost
            - cluster.initial_master_nodes=elasticsearch
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
        expose:
            - 9200
